# Generated by Django 2.1.8 on 2019-05-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthqquser',
            name='is_delete',
        ),
    ]
