# Generated by Django 2.1.8 on 2019-06-11 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20190611_1711'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0003_auto_20190611_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评论点赞表',
                'verbose_name_plural': '评论点赞表',
                'db_table': 'tb_comment_like',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='单价')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('is_commented', models.BooleanField(default=False, verbose_name='是否评价完成')),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
                'db_table': 'tb_order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('oid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('total_count', models.IntegerField(default=1, verbose_name='订单商品总数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='商品总金额')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单运费')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '货到付款'), (2, '支付宝')], default=1, verbose_name='支付方式')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '代发货'), (3, '待收货'), (4, '待评价'), (5, '已完成'), (6, '已取消')], default=1, verbose_name='订单状态')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Address', verbose_name='用户收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
                'db_table': 'tb_order_info',
            },
        ),
        migrations.CreateModel(
            name='SKUComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.TextField(default='', verbose_name='评价内容')),
                ('score', models.SmallIntegerField(choices=[(0, '0分'), (1, '20分'), (2, '40分'), (3, '60分'), (4, '80分'), (5, '100分')], default=5, verbose_name='满意度评分')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名评价')),
                ('total_likes', models.IntegerField(default=0, verbose_name='点赞总数')),
                ('total_comments', models.IntegerField(default=0, verbose_name='评论总数')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goodscomments', to='goods.Goods', verbose_name='商品SPU')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skucomments', to='goods.SKU', verbose_name='商品SKU')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
            ],
            options={
                'verbose_name': 'SKU商品评价表',
                'verbose_name_plural': 'SKU商品评价表',
                'db_table': 'tb_sku_comments',
            },
        ),
        migrations.CreateModel(
            name='SubComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.TextField(default='', verbose_name='评论内容')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcomments', to='orders.SKUComments', verbose_name='关联评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'verbose_name': '评论子表',
                'verbose_name_plural': '评论子表',
                'db_table': 'tb_sub_comments',
            },
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='orders.OrderInfo', verbose_name='关联订单号'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.SKU', verbose_name='订单商品'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='orders.SKUComments', verbose_name='关联评论'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='点赞人'),
        ),
    ]
