# Generated by Django 2.1.8 on 2019-06-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skucomments',
            name='goods',
        ),
    ]
