# Generated by Django 2.1.8 on 2019-06-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_skucomments_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='skucomments',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='allcomments', to='orders.OrderInfo', verbose_name='关联订单编号'),
        ),
    ]
