# Generated by Django 2.1.8 on 2019-06-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190611_1711'),
        ('orders', '0003_skucomments_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='skucomments',
            name='goods',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='spucomments', to='goods.Goods', verbose_name='商品spu'),
        ),
    ]
