# Generated by Django 2.1.8 on 2019-05-29 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_area'),
        ('users', '0002_user_email_active'),
    ]

    operations = [

    ]
