# Generated by Django 2.1.8 on 2019-06-11 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_area'),
        ('users', '0003_auto_20190529_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(help_text='地址名称', max_length=20, verbose_name='地址名称')),
                ('receiver', models.CharField(help_text='收货人', max_length=20, verbose_name='收货人')),
                ('place', models.CharField(help_text='详细地址', max_length=50, verbose_name='详细地址')),
                ('mobile', models.CharField(help_text='手机', max_length=11, verbose_name='手机')),
                ('tel', models.CharField(blank=True, default='', help_text='固定电话', max_length=20, null=True, verbose_name='固定电话')),
                ('email', models.CharField(blank=True, default='', help_text='电子邮箱', max_length=30, null=True, verbose_name='电子邮箱')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('city', models.ForeignKey(help_text='市', on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='areas.Area', verbose_name='市')),
                ('district', models.ForeignKey(help_text='区', on_delete=django.db.models.deletion.PROTECT, related_name='district_addresses', to='areas.Area', verbose_name='区')),
                ('province', models.ForeignKey(help_text='省', on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='areas.Area', verbose_name='省')),
                ('user', models.ForeignKey(help_text='关联用户', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'tb_address',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.OneToOneField(blank=True, help_text='默认收货地址', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.Address', verbose_name='默认收货地址'),
        ),
    ]
