# Generated by Django 2.1.8 on 2019-05-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
