# Generated by Django 2.1.8 on 2019-05-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0002_auto_20190528_2243'),
    ]

    operations = [

    ]
