# Generated by Django 2.1.8 on 2019-05-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='contentcategory',
            name='is_delete',
        ),
    ]
