# Generated by Django 2.1.8 on 2019-06-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20190530_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='contentcategory',
            name='is_delete',
        ),
    ]
